Repository OpenChartProject/OpenChart, pull requests merged in 2020-04, with the labels that each got.

#1 Add OS specific Makefile fixes
  Makefile
Labels: enhancement

#5 Update README
  README.md
Labels: documentation

#2 Add contributors guide
  CONTRIBUTING.md
Labels: documentation

#6 Add a logo for OpenChart
  OpenChart/OpenChart.csproj
  OpenChart/assets/icons/AppIcon.ico
  OpenChart/assets/icons/Logo.png
  OpenChart/assets/icons/Logo@0.33x.png
  OpenChart/src/UI/MainWindow.cs
Labels: enhancement

#7 Replace travis with action
  .github/workflows/build-and-test.yml
  .travis.yml
Labels: dev

#8 Setup publish config and GitHub action
  .github/workflows/build-and-test.yml
  .github/workflows/publish.yml
  .gitignore
  Makefile
  OpenChart/OpenChart.csproj
  README.md
Labels: dev

#9 Update branding and README
  OpenChart/assets/icons/AppIcon.ico
  OpenChart/assets/icons/Logo.png
  OpenChart/assets/icons/Logo@0.33x.png
  README.md
  branding/LICENSE
  branding/Quicksand-VariableFont_wght.ttf
  branding/README.md
  branding/banner.png
  branding/banner.xcf
  branding/banner_small.png
  branding/logo.png
  branding/logo.svg
Labels: documentation

#10 Build the foundation for handling different file formats
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartConverter.cs
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartFormatHandler.cs
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartSerializer.cs
  OpenChart.Tests/src/Formats/TestFormatManager.cs
  OpenChart/src/App.cs
  OpenChart/src/Charting/BPM.cs
  OpenChart/src/Charting/Chart.cs
  OpenChart/src/Charting/ChartObject.cs
  OpenChart/src/Charting/Timing.cs
  OpenChart/src/Formats/FormatManager.cs
  OpenChart/src/Formats/IFormatConverter.cs
  OpenChart/src/Formats/IFormatHandler.cs
  OpenChart/src/Formats/IFormatSerializer.cs
  OpenChart/src/Formats/OpenChart/v0.1/FileData.cs
  OpenChart/src/Formats/OpenChart/v0.1/FileMetadata.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartConverter.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartFormatHandler.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartSerializer.cs
  OpenChart/src/Formats/README.md
  OpenChart/src/Noteskins/KeyModeSkin.cs
  OpenChart/src/Noteskins/NoteSkin.cs
  OpenChart/src/Noteskins/NoteSkinKey.cs
  OpenChart/src/Noteskins/NoteSkinManager.cs
  docs/FileFormats.md
  docs/img/file_format_class_diagram.png
Labels: docs, scaffolding

#11 Add basic chart objects, logic for adding objects
  OpenChart.Tests/src/Charting/Objects/Dummy.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseLongObject.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseObject.cs
  OpenChart.Tests/src/Charting/TestBPM.cs
  OpenChart.Tests/src/Charting/TestChart.cs
  OpenChart.Tests/src/Charting/TestChartObject.cs
  OpenChart.Tests/src/Charting/TestChartUtils.cs
  OpenChart.Tests/src/Charting/TestTiming.cs
  OpenChart/src/Charting/BPM.cs
  OpenChart/src/Charting/Chart.cs
  OpenChart/src/Charting/ChartException.cs
  OpenChart/src/Charting/ChartObject.cs
  OpenChart/src/Charting/ChartUtils.cs
  OpenChart/src/Charting/Objects/BaseLongObject.cs
  OpenChart/src/Charting/Objects/BaseObject.cs
  OpenChart/src/Charting/Objects/HoldNote.cs
  OpenChart/src/Charting/Objects/TapNote.cs
  OpenChart/src/Charting/Timing.cs
Labels: scaffolding

#27 Add Projects
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartConverter.cs
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartSerializer.cs
  OpenChart/src/Formats/ConverterException.cs
  OpenChart/src/Formats/FileFormatException.cs
  OpenChart/src/Formats/IFormatConverter.cs
  OpenChart/src/Formats/IFormatHandler.cs
  OpenChart/src/Formats/IFormatSerializer.cs
  OpenChart/src/Formats/IProjectConverter.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/ChartData.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/ProjectData.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/ProjectMetadata.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/SongData.cs
  OpenChart/src/Formats/OpenChart/v0.1/FileData.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartConverter.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartFormatHandler.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartSerializer.cs
  OpenChart/src/Formats/SerializerException.cs
  OpenChart/src/Projects/Project.cs
  OpenChart/src/Songs/SongMetadata.cs
  docs/FileFormats.md
  docs/img/file_format_class_diagram.png
  docs/img/file_format_diagram.dia
  docs/img/file_format_diagram.png
Labels: enhancement, 📌 import / export, 📌 projects

#30 Move commonly used properties into their own classes
  OpenChart.Tests/src/Charting/Objects/Dummy.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseLongObject.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseObject.cs
  OpenChart.Tests/src/Charting/TestBeat.cs
  OpenChart.Tests/src/Charting/TestBeatDuration.cs
  OpenChart.Tests/src/Charting/TestChart.cs
  OpenChart.Tests/src/Charting/TestChartUtils.cs
  OpenChart.Tests/src/Charting/TestKey.cs
  OpenChart.Tests/src/Charting/TestKeyCount.cs
  OpenChart.Tests/src/Charting/TestTiming.cs
  OpenChart/src/Charting/BPM.cs
  OpenChart/src/Charting/Beat.cs
  OpenChart/src/Charting/BeatDuration.cs
  OpenChart/src/Charting/Chart.cs
  OpenChart/src/Charting/ChartUtils.cs
  OpenChart/src/Charting/KeyCount.cs
  OpenChart/src/Charting/KeyIndex.cs
  OpenChart/src/Charting/Objects/BaseLongObject.cs
  OpenChart/src/Charting/Objects/BaseObject.cs
  OpenChart/src/Charting/Objects/HoldNote.cs
  OpenChart/src/Charting/Objects/TapNote.cs
  OpenChart/src/Charting/Timing.cs
  OpenChart/src/Formats/OpenChart/v0.1/Converters.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/ChartData.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartSerializer.cs
Labels: dev

#34 Create a generic container for beat-sorted objects
  OpenChart.Tests/src/Charting/TestBeat.cs
  OpenChart.Tests/src/Charting/TestBeatDuration.cs
  OpenChart.Tests/src/Charting/TestBeatObjectList.cs
  OpenChart.Tests/src/Charting/TestChart.cs
  OpenChart.Tests/src/Charting/TestKey.cs
  OpenChart.Tests/src/Charting/TestKeyCount.cs
  OpenChart/src/Charting/BPM.cs
  OpenChart/src/Charting/Beat.cs
  OpenChart/src/Charting/BeatDuration.cs
  OpenChart/src/Charting/BeatObjectList.cs
  OpenChart/src/Charting/Chart.cs
  OpenChart/src/Charting/IBeatObject.cs
  OpenChart/src/Charting/IChangeNotifier.cs
  OpenChart/src/Charting/KeyCount.cs
  OpenChart/src/Charting/KeyIndex.cs
  OpenChart/src/Charting/Objects/BaseObject.cs
Labels: dev, 📌 charting

#38 Do some spring cleaning to use consistent coding styles
  .vscode/settings.json
  CONTRIBUTING.md
  OpenChart.Tests/src/Charting/Objects/Dummy.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseLongObject.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseObject.cs
  OpenChart.Tests/src/Charting/TestBPM.cs
  OpenChart.Tests/src/Charting/TestChart.cs
  OpenChart.Tests/src/Charting/TestChartUtils.cs
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartConverter.cs
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartFormatHandler.cs
  OpenChart.Tests/src/Formats/OpenChart/TestOpenChartSerializer.cs
  OpenChart.Tests/src/Formats/TestFormatManager.cs
  OpenChart/src/App.cs
  OpenChart/src/Charting/BPM.cs
  OpenChart/src/Charting/Beat.cs
  OpenChart/src/Charting/BeatDuration.cs
  OpenChart/src/Charting/BeatObjectList.cs
  OpenChart/src/Charting/Chart.cs
  OpenChart/src/Charting/ChartException.cs
  OpenChart/src/Charting/ChartUtils.cs
  OpenChart/src/Charting/KeyCount.cs
  OpenChart/src/Charting/KeyIndex.cs
  OpenChart/src/Charting/Objects/BaseLongObject.cs
  OpenChart/src/Charting/Objects/BaseObject.cs
  OpenChart/src/Charting/Objects/HoldNote.cs
  OpenChart/src/Charting/Objects/TapNote.cs
  OpenChart/src/Formats/ConverterException.cs
  OpenChart/src/Formats/FileFormatException.cs
  OpenChart/src/Formats/FormatManager.cs
  OpenChart/src/Formats/IFormatHandler.cs
  OpenChart/src/Formats/IFormatSerializer.cs
  OpenChart/src/Formats/IProjectConverter.cs
  OpenChart/src/Formats/OpenChart/v0.1/Converters.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/ChartData.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/ProjectData.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/SongData.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartConverter.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartFormatHandler.cs
  OpenChart/src/Formats/OpenChart/v0.1/OpenChartSerializer.cs
  OpenChart/src/Formats/SerializerException.cs
  OpenChart/src/Noteskins/KeyModeSkin.cs
  OpenChart/src/Noteskins/NoteSkin.cs
  OpenChart/src/Noteskins/NoteSkinManager.cs
  OpenChart/src/Program.cs
  OpenChart/src/Projects/Project.cs
  OpenChart/src/Songs/SongMetadata.cs
  OpenChart/src/UI/Assets/ImageAsset.cs
  OpenChart/src/UI/MainWindow.cs
Labels: dev

#36 Organize the Charting namespace
  OpenChart.Tests/src/Charting/Objects/Dummy.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseLongObject.cs
  OpenChart.Tests/src/Charting/Objects/TestBaseObject.cs
  OpenChart.Tests/src/Charting/Properties/TestBPM.cs
  OpenChart.Tests/src/Charting/Properties/TestBeat.cs
  OpenChart.Tests/src/Charting/Properties/TestBeatDuration.cs
  OpenChart.Tests/src/Charting/Properties/TestKey.cs
  OpenChart.Tests/src/Charting/Properties/TestKeyCount.cs
  OpenChart.Tests/src/Charting/TestBeatObjectList.cs
  OpenChart.Tests/src/Charting/TestChartUtils.cs
  OpenChart/src/Charting/BeatObjectList.cs
  OpenChart/src/Charting/Chart.cs
  OpenChart/src/Charting/ChartUtils.cs
  OpenChart/src/Charting/Exceptions/ChartException.cs
  OpenChart/src/Charting/Exceptions/ObjectOverlapException.cs
  OpenChart/src/Charting/Objects/BaseLongObject.cs
  OpenChart/src/Charting/Objects/BaseObject.cs
  OpenChart/src/Charting/Objects/HoldNote.cs
  OpenChart/src/Charting/Objects/IPlacementValidator.cs
  OpenChart/src/Charting/Objects/TapNote.cs
  OpenChart/src/Charting/Properties/BPM.cs
  OpenChart/src/Charting/Properties/Beat.cs
  OpenChart/src/Charting/Properties/BeatDuration.cs
  OpenChart/src/Charting/Properties/IBeatDurationObject.cs
  OpenChart/src/Charting/Properties/IBeatObject.cs
  OpenChart/src/Charting/Properties/IChangeNotifier.cs
  OpenChart/src/Charting/Properties/IKeyedObject.cs
  OpenChart/src/Charting/Properties/KeyCount.cs
  OpenChart/src/Charting/Properties/KeyIndex.cs
  OpenChart/src/Formats/OpenChart/v0.1/Converters.cs
  OpenChart/src/Formats/OpenChart/v0.1/Data/ChartData.cs
Labels: dev, 📌 charting
